# Docs: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy ASP.NET App to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      # Pull source code
      - uses: actions/checkout@v4

      # Show all files in repo (debugging if .sln not found)
      - name: List repo files
        run: dir -Recurse

      # Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      # Setup NuGet
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      # Restore NuGet packages (change MyApp.sln to your actual solution file)
      - name: Restore NuGet packages
        run: nuget restore MyApp.sln

      # Build and publish to folder
      - name: Publish app
        run: msbuild MyApp.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:PublishDir="$(Build.ArtifactStagingDirectory)\published"

      # Upload published files as artifact
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: $(Build.ArtifactStagingDirectory)\published\**

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read # Required for actions/checkout

    steps:
      # Download artifact from build job
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ASP-app

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'babu'
          slot-name: 'Production'
          package: .
